#!/bin/sh /etc/rc.common
# The Aeolus agent (0040). Its log: logread -e aeolus

START=99
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/aeolus-agent
	procd_set_param respawn 3600 5 0
	procd_set_param stderr 1
	procd_close_instance
}
